import { ChangeEvent, useEffect, useRef, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { Bot, Copy, Paperclip, Pin, Plus, RefreshCcw, Send, Square, Sparkles, ThumbsDown, ThumbsUp, X } from "lucide-react";
import { agents, projects, documents } from "../data/mockData";
import { Button, Badge } from "../components/ui";
import { ChatMessage } from "../types";
import { getAssistantHistory, saveAssistantHistory, streamAssistantReply } from "../services/mockApi";
import { useAuth } from "../context/AuthContext";

export default function AIAssistant(){
 const {user}=useAuth(); const [params]=useSearchParams();
 const [agentId,setAgentId]=useState(params.get("agent")||"finance"); const [projectId,setProjectId]=useState(params.get("project")||projects[0]?.id||""); const [input,setInput]=useState(""); const [files,setFiles]=useState<{id:string;name:string}[]>([]); const [messages,setMessages]=useState<ChatMessage[]>([]); const [streaming,setStreaming]=useState(false); const [error,setError]=useState(""); const end=useRef<HTMLDivElement>(null);

 useEffect(()=>{if(user)void getAssistantHistory(user).then(saved=>setMessages(saved.length?saved:[{id:"welcome",role:"assistant",content:"Welcome to the Finance AI workspace. Select a project and agent, attach source files, then ask your question.",createdAt:new Date().toISOString(),limitations:"This frontend demo does not execute a production LLM or file parser."}]))},[user]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:"smooth"})},[messages]); useEffect(()=>{if(user&&messages.length)void saveAssistantHistory(user,messages)},[messages,user]);

 const send=async()=>{if(!input.trim()||streaming)return;const text=input.trim();setInput("");setError("");const userMsg:ChatMessage={id:`u-${Date.now()}`,role:"user",content:text,createdAt:new Date().toISOString()};const id=`a-${Date.now()+1}`;setMessages(m=>[...m,userMsg,{id,role:"assistant",content:"",createdAt:new Date().toISOString()}]);setStreaming(true);try{const gen=await streamAssistantReply({message:text,agentId,projectId,fileIds:files.map(f=>f.id),history:messages});for await(const chunk of gen)setMessages(m=>m.map(x=>x.id===id?{...x,content:x.content+chunk}:x));}catch(e){setError(e instanceof Error?e.message:"AI request failed.");setMessages(m=>m.filter(x=>x.id!==id));}finally{setStreaming(false)}};
 const attach=(e:ChangeEvent<HTMLInputElement>)=>{const allowed=new Set(["xlsx","xls","csv","pdf","docx","txt","json"]);const next=Array.from(e.target.files||[]).map((f,i)=>({id:`upload-${Date.now()}-${i}`,name:f.name})).filter(f=>allowed.has(f.name.split(".").pop()?.toLowerCase()||""));setFiles(current=>[...current,...next]);e.target.value="";};
 const activeProject=projects.find(p=>p.id===projectId); const projectDocs=documents.filter(d=>d.projectId===projectId);
 return <div className="ai-shell"><aside className="ai-history"><div className="ai-title"><Sparkles size={17}/> AI Assistant</div><Button onClick={()=>setMessages([])}><Plus size={15}/> New conversation</Button><div className="eyebrow">RECENT</div>{messages.filter(m=>m.role==="user").slice(-8).reverse().map(m=><button className="history-item" key={m.id} onClick={()=>setInput(m.content)}>{m.content.slice(0,42)}<span>saved</span></button>)}</aside>
 <main className="ai-main"><div className="ai-top"><div><div className="eyebrow">PROJECT AI WORKSPACE</div><h1>Professional copilot</h1></div><div className="ai-selects"><select value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={agentId} onChange={e=>setAgentId(e.target.value)}>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div></div>
 <div className="ai-context"><span>Project: {activeProject?.name}</span><span>Client: {activeProject?.clientName}</span><span>Project documents: {projectDocs.length}</span><Badge tone="info">Context aware</Badge></div>
 {error&&<div className="error-box">{error}</div>}
 <div className="chat-scroll">{messages.map(m=><div className={m.role==="user"?"chat-row user":"chat-row"} key={m.id}><div className={m.role==="user"?"chat-avatar user":"chat-avatar"}>{m.role==="user"?"U":<Bot size={16}/>}</div><div className="chat-bubble">{m.role==="assistant"&&<div className="assistant-label">{agents.find(a=>a.id===agentId)?.name||"Finance AI"}</div>}<div className="chat-content">{m.content||"Thinking…"}</div>{m.role==="assistant"&&m.content&&<div className="evidence-grid"><div><strong>Project</strong><span>{activeProject?.name}</span></div><div><strong>Sources</strong><span>{files.length?files.map(f=>f.name).join(", "):projectDocs.map(d=>d.name).join(", ")||"No files"}</span></div><div><strong>Method</strong><span>Project-aware, evidence-first response structure.</span></div><div><strong>Limitations</strong><span>{m.limitations||"Validate before professional use."}</span></div></div>}{m.role==="assistant"&&m.content&&<div className="chat-actions"><button onClick={()=>navigator.clipboard?.writeText(m.content)}><Copy size={14}/></button><button onClick={()=>setInput("Please regenerate the previous answer with more detail.")}><RefreshCcw size={14}/></button><button><ThumbsUp size={14}/></button><button><ThumbsDown size={14}/></button><button><Pin size={14}/></button></div>}</div></div>)}<div ref={end}/></div>
 <div className="chat-composer"><div className="composer-attachment"><label className="attachment-label"><Paperclip size={17}/><span>Attach XLSX, CSV, PDF, DOCX, TXT or JSON</span><input type="file" hidden multiple accept=".xlsx,.xls,.csv,.pdf,.docx,.txt,.json" onChange={attach}/></label>{files.map(f=><span className="attachment-chip" key={f.id}>{f.name}<button onClick={()=>setFiles(current=>current.filter(x=>x.id!==f.id))}><X size={11}/></button></span>)}</div><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send()}}} placeholder="Ask about financial performance, anomalies, tax, audit, valuation or uploaded documents..."/><div className="composer-bottom"><span>AI output is assistive analysis. Review before professional use.</span><div><button className="icon-btn" onClick={()=>setInput("")}><Square size={14}/></button><button className="icon-btn" onClick={()=>void send()} disabled={streaming}>{streaming?<Square size={16}/>:<Send size={16}/>}</button></div></div></div></main></div>;
}