import { useEffect, useRef, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { Bot, Copy, Download, Paperclip, Pin, Plus, RefreshCcw, Send, Square, Sparkles, ThumbsDown, ThumbsUp } from "lucide-react";
import { agents } from "../data/mockData";
import { Button, Badge } from "../components/ui";
import { ChatMessage } from "../types";
import { streamAssistantReply } from "../services/mockApi";

export default function AIAssistant(){
 const [params]=useSearchParams();const defaultAgent=params.get("agent")||"finance";const [agentId,setAgentId]=useState(defaultAgent);const [input,setInput]=useState("");const [messages,setMessages]=useState<ChatMessage[]>([{id:"welcome",role:"assistant",content:"Welcome to the Finance AI workspace. Select an agent and project context, then ask a question. I’ll structure the response around answer, calculation, source, evidence, assumptions and limitations.",createdAt:new Date().toISOString(),limitations:"Demo response. Validate outputs with authorized source documents."}]);const [streaming,setStreaming]=useState(false);const end=useRef<HTMLDivElement>(null);
useEffect(()=>end.current?.scrollIntoView({behavior:"smooth"}),[messages]);
const send=async()=>{if(!input.trim()||streaming)return;const text=input;setInput("");setMessages(m=>[...m,{id:`u-${Date.now()}`,role:"user",content:text,createdAt:new Date().toISOString()}]);setStreaming(true);const id=`a-${Date.now()}`;setMessages(m=>[...m,{id,role:"assistant",content:"",createdAt:new Date().toISOString(),evidence:[{source:"Aster_Annual_Report_FY25.pdf",page:47,excerpt:"Demo evidence placeholder — connect to document extraction service for real source grounding."}],calculation:"Revenue growth = (Current period − Prior period) / Prior period × 100",assumptions:["Source data is complete and consistently classified."],limitations:"Mock mode: no real document retrieval has been executed."}]);try{const gen=await streamAssistantReply(text,agentId);for await(const chunk of gen)setMessages(m=>m.map(x=>x.id===id?{...x,content:x.content+chunk}:x));}finally{setStreaming(false)}};
return <div className="ai-shell"><aside className="ai-history"><div className="ai-title"><Sparkles size={17}/> AI Assistant</div><Button><Plus size={15}/> New conversation</Button><div className="eyebrow">RECENT</div>{["FY26 financial review","Aster cash flow analysis","Orion DCF assumptions","Tax reconciliation"].map(x=><button className="history-item" key={x}>{x}<span>today</span></button>)}</aside>
<main className="ai-main"><div className="ai-top"><div><div className="eyebrow">PROJECT AI WORKSPACE</div><h1>Professional copilot</h1></div><select value={agentId} onChange={e=>setAgentId(e.target.value)}>{agents.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></div><div className="ai-context"><span>Project: FY26 Financial Health Review</span><span>Client: Aster Manufacturing Pvt Ltd</span><span>Documents: 3</span><Badge tone="info">Source-backed mode</Badge></div><div className="chat-scroll">{messages.map(m=><div className={m.role==="user"?"chat-row user":"chat-row"} key={m.id}><div className={m.role==="user"?"chat-avatar user":"chat-avatar"}>{m.role==="user"?"U":<Bot size={16}/>}</div><div className="chat-bubble">{m.role==="assistant"&&<div className="assistant-label">{agents.find(a=>a.id===agentId)?.name||"Finance AI"}</div>}<div className="chat-content">{m.content}</div>{m.evidence&&<div className="evidence-grid"><div><strong>Source</strong><span>{m.evidence[0].source} · p.{m.evidence[0].page}</span></div><div><strong>Calculation</strong><span>{m.calculation}</span></div><div><strong>Evidence</strong><span>{m.evidence[0].excerpt}</span></div><div><strong>Assumptions</strong><span>{m.assumptions?.join(" ")}</span></div></div>}{m.role==="assistant"&&<div className="chat-actions"><button><Copy size={14}/></button><button><RefreshCcw size={14}/></button><button><ThumbsUp size={14}/></button><button><ThumbsDown size={14}/></button><button><Pin size={14}/></button><button><Download size={14}/></button></div>}</div></div>)}<div ref={end}/></div><div className="chat-composer"><div className="composer-attachment"><Paperclip size={17}/><span>Attach XLSX, CSV, PDF, DOCX, TXT or JSON</span></div><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ask about financial performance, anomalies, tax, audit, valuation or your uploaded documents..."/><div className="composer-bottom"><span>AI output is assistive analysis. Review before professional use.</span><div><button className="icon-btn"><Download size={16}/></button><button className="icon-btn">{streaming?<Square size={16}/>:<Send size={16}/>}</button></div></div></div></main></div>}