import { useEffect, useState } from "react";
import { Plus, Search, MoreHorizontal, Building2 } from "lucide-react";
import { Badge, Button, Modal, PageHeader, EmptyState } from "../components/ui";
import { Client } from "../types";
import { useAuth } from "../context/AuthContext";

const API_BASE=(import.meta.env.VITE_API_URL||"").replace(/\/$/,"");
async function loadClients(userId:string){const r=await fetch(`${API_BASE}/api/clients`,{headers:{"x-user-id":userId}});if(!r.ok)throw new Error("Unable to load clients.");return r.json() as Promise<Client[]>;}
async function createClient(userId:string,payload:Partial<Client>){const r=await fetch(`${API_BASE}/api/clients`,{method:"POST",headers:{"Content-Type":"application/json","x-user-id":userId},body:JSON.stringify(payload)});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error||"Unable to create client.");}return r.json() as Promise<Client>;}

export default function Clients(){
 const {user}=useAuth();const [rows,setRows]=useState<Client[]>([]);const [q,setQ]=useState("");const [open,setOpen]=useState(false);const [name,setName]=useState("");const [company,setCompany]=useState("");const [industry,setIndustry]=useState("Technology");const [error,setError]=useState("");
 useEffect(()=>{if(!user)return;void loadClients(user.id).then(setRows).catch(()=>setRows([]));},[user]);
 const add=async()=>{if(!user||!company.trim())return;try{const next=await createClient(user.id,{name:name||"New contact",company,industry});setRows(r=>[next,...r]);setName("");setCompany("");setOpen(false);setError("");}catch(e){setError(e instanceof Error?e.message:"Unable to create client.");}};
 const filtered=rows.filter(c=>(c.company+" "+c.name+" "+c.industry).toLowerCase().includes(q.toLowerCase()));
 return <><PageHeader eyebrow="CRM" title="Clients" description="Manage client records, workspaces, documents, projects and engagement history." action={<Button onClick={()=>setOpen(true)}><Plus size={16}/> New client</Button>}/>{error&&<div className="error-box">{error}</div>}<div className="toolbar"><div className="search-box light"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search clients..."/></div><Button variant="secondary">Import CSV</Button></div>
 <div className="table-panel"><table><thead><tr><th>Client</th><th>Industry</th><th>Financial year</th><th>Status</th><th>Team</th><th>Projects</th><th>Documents</th><th></th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><div className="table-primary"><div className="table-avatar"><Building2 size={15}/></div><div><strong>{c.company}</strong><span>{c.name} · {c.email}</span></div></div></td><td>{c.industry}</td><td>{c.fy}</td><td><Badge tone={c.status==="Active"?"success":c.status==="Onboarding"?"warning":"default"}>{c.status}</Badge></td><td>{c.team}</td><td>{c.projects}</td><td>{c.documents}</td><td><button className="icon-btn"><MoreHorizontal size={17}/></button></td></tr>)}</tbody></table>{!filtered.length&&<EmptyState title="No clients found" description="Try a different search."/ >}</div>
 <Modal open={open} onClose={()=>setOpen(false)} title="Create client"><div className="form-stack"><label>Company name<input value={company} onChange={e=>setCompany(e.target.value)} required/></label><label>Primary contact<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Industry<select value={industry} onChange={e=>setIndustry(e.target.value)}><option>Technology</option><option>Manufacturing</option><option>Retail</option><option>Infrastructure</option><option>Professional Services</option></select></label><div className="modal-actions"><Button variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={()=>void add()}>Create client</Button></div></div></Modal></>;
}
