import { useState } from "react";
import { CheckCircle2, ChevronRight, FileCheck2, LockKeyhole, RefreshCw, Send, ShieldCheck } from "lucide-react";

const steps=["Profile","Income","Deductions","Assets","Review","File"];
export default function ITRFiling(){
 const [step,setStep]=useState(0); const [validated,setValidated]=useState(false);
 const next=()=>setStep(s=>Math.min(5,s+1));
 return <div className="page">
  <div className="page-header"><div><div className="eyebrow">ITR FILING</div><h1>Prepare your Income Tax Return</h1><p className="page-subtitle">Assessment Year 2026-27 · Assisted preparation with reviewable calculations and evidence.</p></div><div className="secure-pill"><LockKeyhole size={14}/> Your data stays under your account</div></div>
  <div className="itr-stepper">{steps.map((s,i)=><div className={i<=step?"itr-step active":"itr-step"} key={s}><div className="itr-number">{i<step?"✓":i+1}</div><span>{s}</span>{i<5&&<ChevronRight size={14}/>}</div>)}</div>
  <section className="panel">
   {step===0&&<><h2>Taxpayer profile</h2><p className="panel-subtitle">Confirm the information that will be used to prepare your return.</p><div className="form-grid"><label>PAN<input placeholder="ABCDE1234F"/></label><label>Assessment Year<select><option>2026-27</option><option>2025-26</option></select></label><label>Residential status<select><option>Resident</option><option>Non-resident</option><option>Resident but not ordinarily resident</option></select></label><label>Taxpayer type<select><option>Individual</option><option>Individual with business/profession</option></select></label></div></>}
   {step===1&&<><h2>Income & tax credits</h2><p className="panel-subtitle">Add or review income sources and tax deducted at source.</p><div className="feature-grid"><div><strong>Salary</strong><span>₹9,60,000 · Form 16 ready</span></div><div><strong>Interest</strong><span>₹84,000 · Bank statements</span></div><div><strong>Capital gains</strong><span>₹2,40,000 · Investment records</span></div><div><strong>TDS</strong><span>₹96,000 · To be reconciled</span></div></div></>}
   {step===2&&<><h2>Deductions & exemptions</h2><p className="panel-subtitle">Review eligible deductions and supporting documents before calculation.</p><div className="form-grid"><label>Section 80C<input value="150000" readOnly/></label><label>Health insurance<input value="25000" readOnly/></label><label>Home loan interest<input value="0" readOnly/></label><label>Other deductions<input value="0" readOnly/></label></div></>}
   {step===3&&<><h2>Assets & capital gains</h2><p className="panel-subtitle">Review investment and property information relevant to the return.</p><div className="feature-grid"><div><strong>Equity / mutual funds</strong><span>4 investment accounts connected to your asset register.</span></div><div><strong>Property</strong><span>1 property record available for review.</span></div><div><strong>Bank accounts</strong><span>2 accounts marked for verification.</span></div><div><strong>Foreign assets</strong><span>Not reported in this draft.</span></div></div></>}
   {step===4&&<><h2>Review & validation</h2><p className="panel-subtitle">Local checks run before any external filing integration is called.</p><div className="validation-box"><div><CheckCircle2 size={20}/><div><strong>Income totals reconcile</strong><span>Salary, interest and capital-gain inputs are internally consistent.</span></div></div><div><CheckCircle2 size={20}/><div><strong>Mandatory profile fields present</strong><span>Complete the final taxpayer review before submission.</span></div></div><div><ShieldCheck size={20}/><div><strong>External submission requires consent</strong><span>Production ERI integration will request taxpayer consent before prefill/submission.</span></div></div></div><button className="btn btn-secondary" onClick={()=>setValidated(true)}><RefreshCw size={15}/> Run validation</button>{validated&&<div className="success-box">Validation passed for the current draft. Final validation must still be performed immediately before submission.</div>}</>}
   {step===5&&<><h2>File & e-Verify</h2><p className="panel-subtitle">The final stage connects the prepared return to the approved filing integration.</p><div className="filing-timeline"><div><FileCheck2 size={20}/><strong>Prepare ITR payload</strong><span>Map approved data into the applicable ITR schema.</span></div><div><Send size={20}/><strong>Validate & submit</strong><span>Production integration submits only after required consent and validation.</span></div><div><ShieldCheck size={20}/><strong>e-Verify</strong><span>Complete the applicable taxpayer verification method.</span></div><div><CheckCircle2 size={20}/><strong>Acknowledgement</strong><span>Store transaction and acknowledgement references.</span></div></div><button className="btn btn-primary" disabled>Connect filing provider to submit</button></>}
  </section>
  <div className="wizard-actions">{step>0&&<button className="btn btn-secondary" onClick={()=>setStep(s=>s-1)}>Back</button>}{step<5&&<button className="btn btn-primary" onClick={next}>Continue <ChevronRight size={15}/></button>}</div>
 </div>;
}
