import { useState } from "react";
import { CheckCircle2,ChevronRight,FileCheck2,LockKeyhole,RefreshCw,Send,ShieldCheck } from "lucide-react";
import { createITR,grantITRConsent,validateITR } from "../services/individualApi";
import "../individual.css";
const steps=["Profile","Income","Deductions","Assets","Review","Filing readiness"];
export default function ITRFiling(){
 const [step,setStep]=useState(0);const [validated,setValidated]=useState(false);const [returnId,setReturnId]=useState<string|null>(null);const [consent,setConsent]=useState(false);
 const next=async()=>{if(step===4&&!returnId){const r=await createITR();setReturnId(r.id);}setStep(s=>Math.min(5,s+1));};
 const runValidation=async()=>{const id=returnId||(await createITR()).id;if(!returnId)setReturnId(id);await validateITR(id);setValidated(true);};
 const giveConsent=async()=>{if(returnId){await grantITRConsent(returnId);setConsent(true);}};
 return <div className="page"><div className="page-header"><div><div className="eyebrow">ITR FILING</div><h1>Prepare your Income Tax Return</h1><p className="page-subtitle">Assessment Year 2026-27 · Assisted preparation with reviewable calculations and evidence.</p></div><div className="secure-pill"><LockKeyhole size={14}/> Your data stays under your account</div></div>
 <div className="itr-stepper">{steps.map((s,i)=><div className={i<=step?"itr-step active":"itr-step"} key={s}><div className="itr-number">{i<step?"✓":i+1}</div><span>{s}</span>{i<5&&<ChevronRight size={14}/>}</div>)}</div>
 <section className="panel">
 {step===0&&<><h2>Taxpayer profile</h2><p className="panel-subtitle">Confirm the information that will be used to prepare your return.</p><div className="form-grid"><label>PAN<input placeholder="ABCDE1234F"/></label><label>Assessment Year<select><option>2026-27</option><option>2025-26</option></select></label><label>Residential status<select><option>Resident</option><option>Non-resident</option><option>Resident but not ordinarily resident</option></select></label><label>Taxpayer type<select><option>Individual</option><option>Individual with business/profession</option></select></label></div></>}
 {step===1&&<><h2>Income & tax credits</h2><p className="panel-subtitle">Review income sources and tax deducted at source.</p><div className="feature-grid"><div><strong>Salary</strong><span>₹9,60,000 · Form 16 ready</span></div><div><strong>Interest</strong><span>₹84,000 · Bank statements</span></div><div><strong>Capital gains</strong><span>₹2,40,000 · Investment records</span></div><div><strong>TDS</strong><span>₹96,000 · To be reconciled</span></div></div></>}
 {step===2&&<><h2>Deductions & exemptions</h2><p className="panel-subtitle">Review eligible deductions and supporting documents.</p><div className="form-grid"><label>Section 80C<input value="150000" readOnly/></label><label>Health insurance<input value="25000" readOnly/></label><label>Home loan interest<input value="0" readOnly/></label><label>Other deductions<input value="0" readOnly/></label></div></>}
 {step===3&&<><h2>Assets & capital gains</h2><p className="panel-subtitle">Review investment and property information relevant to the return.</p><div className="feature-grid"><div><strong>Equity / mutual funds</strong><span>Use My Assets to maintain investment records.</span></div><div><strong>Property</strong><span>Property records can be referenced during review.</span></div><div><strong>Bank accounts</strong><span>Mark accounts for verification before filing.</span></div><div><strong>Foreign assets</strong><span>Declare where applicable; do not infer from incomplete data.</span></div></div></>}
 {step===4&&<><h2>Review & validation</h2><p className="panel-subtitle">Local checks run before any external filing integration is called.</p><div className="validation-box"><div><CheckCircle2 size={20}/><div><strong>Income totals reconcile</strong><span>Current draft has internally consistent example inputs.</span></div></div><div><CheckCircle2 size={20}/><div><strong>Mandatory profile fields present</strong><span>Complete the final taxpayer review before submission.</span></div></div><div><ShieldCheck size={20}/><div><strong>External submission requires consent</strong><span>Production ERI integration will request taxpayer consent before prefill/submission.</span></div></div></div><button className="btn btn-secondary" onClick={runValidation}><RefreshCw size={15}/> Run validation</button>{validated&&<div className="success-box">Local validation passed and the draft is marked READY_TO_FILE.</div>}</>}
 {step===5&&<><h2>Ready to File</h2><p className="panel-subtitle">This draft stops at filing readiness. External submission is unavailable until an approved filing / ERI provider is configured.</p><div className="filing-timeline"><div><FileCheck2 size={20}/><strong>Generate filing data</strong><span>Prepare return data for validation against the applicable ITR schema.</span></div><div><Send size={20}/><strong>Approved provider submission</strong><span>Submission remains unavailable until an approved integration is connected.</span></div><div><ShieldCheck size={20}/><strong>e-Verification</strong><span>Available only after provider submission.</span></div><div><CheckCircle2 size={20}/><strong>Acknowledgement</strong><span>Recorded only after filing confirmation from the provider.</span></div></div>{!consent?<button className="btn btn-secondary" onClick={giveConsent} disabled={!returnId}>Record taxpayer consent</button>:<div className="success-box">Consent recorded for this draft. No return has been submitted.</div>}<button className="btn btn-primary" disabled>Filing provider not connected</button></>}
 </section><div className="wizard-actions">{step>0&&<button className="btn btn-secondary" onClick={()=>setStep(s=>s-1)}>Back</button>}{step<5&&<button className="btn btn-primary" onClick={next}>Continue <ChevronRight size={15}/></button>}</div></div>;
}