import { FileBarChart, FileSpreadsheet, FileText, Presentation, Sparkles } from "lucide-react";
import { Badge, Button, PageHeader } from "../components/ui";
import { useAuth } from "../context/AuthContext";

const professionalReports=[["Aster Financial Health Review","Financial Analysis","Aster Manufacturing Pvt Ltd","FY 2025-26","DOCX"],["Orion Valuation Pack","Investment Report","Orion Software Solutions","FY 2025-26","PPTX"],["Aster Transaction Anomaly Review","Audit Report","Aster Manufacturing Pvt Ltd","Q4 FY26","XLSX"]];
const financeReports=[["Monthly Business Performance","P&L + Cash Flow","Current Business","Sep 2026","PDF"],["GST & Tax Summary","Tax Report","Current Business","FY 2025-26","XLSX"],["Expense & Profitability Review","Business Analysis","Current Business","Q2 FY26","PDF"]];
const individualReports=[["Personal Finance Summary","Personal Finance","My Workspace","Sep 2026","PDF"],["Asset & Liability Overview","Asset Management","My Workspace","FY 2025-26","XLSX"],["Tax / ITR Summary","Tax","My Workspace","AY 2026-27","PDF"]];

function ReportCard({row}:{row:string[]}){const [title,kind,scope,period,format]=row;return <div className="report-card"><div className="report-icon">{format==="XLSX"?<FileSpreadsheet size={20}/>:format==="PPTX"?<Presentation size={20}/>:format==="DOCX"?<FileText size={20}/>:<FileBarChart size={20}/>}</div><div className="report-meta"><Badge tone="info">{kind}</Badge><span>{period}</span></div><h3>{title}</h3><p>{scope} · Executive summary, financial metrics, evidence, assumptions and reviewer notes.</p><div className="report-footer"><Button variant="secondary">Review</Button><span>{format}</span></div></div>}

export default function Reports(){
 const {user}=useAuth();
 const isProfessional=user?.role==="Professional User", isFinance=user?.role==="Finance User";
 const reports=isProfessional?professionalReports:isFinance?financeReports:individualReports;
 return <><PageHeader eyebrow="REPORTING" title={isProfessional?"Professional Reports":isFinance?"Business Reports":"My Financial Reports"} description={isProfessional?"Generate client- and project-specific reports with an auditable review trail.":isFinance?"Generate reports for your own business performance, tax and cash flow.":"Generate private reports for your personal income, assets, liabilities and tax records."} action={<Button><Sparkles size={16}/> New report</Button>}/>
 {isProfessional&&<div className="panel"><div className="panel-head"><div><h2>Professional report context</h2><p>Every report is tied to a client, project and financial year before generation.</p></div></div><div className="builder-strip"><span>1. Select client</span><span>2. Select project</span><span>3. Select financial year</span><span>4. Select report type</span><span>5. Generate → Review → Download</span></div></div>}
 <div className="report-grid">{reports.map((row)=><ReportCard key={row[0]} row={row}/>)}</div>
 <div className="panel"><div className="panel-head"><div><h2>{isProfessional?"Client & project report builder":isFinance?"Business report builder":"Personal report builder"}</h2><p>{isProfessional?"Use approved documents and AI analysis for the selected client/project.":isFinance?"Use your business data to create recurring management reports.":"Use your personal finance data to create private summaries."}</p></div><Button>Create report</Button></div><div className="builder-strip">{isProfessional?<><span>Client</span><span>Project</span><span>Financial Year</span><span>Report Type</span><span>Export PDF / Excel</span></>:isFinance?<><span>Period</span><span>Business data</span><span>Report type</span><span>AI analysis</span><span>Export</span></>:<><span>Period</span><span>Income & expenses</span><span>Assets</span><span>Tax</span><span>Export</span></>}</div></div></>;
}