import { FormEvent,useState } from "react";
import { Link,useNavigate } from "react-router-dom";
import { ArrowLeft,Sparkles } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { ProfessionalRole,Role } from "../types";
import "../individual.css";
const professionalRoles:ProfessionalRole[]=["CA","CS","CFA","Financial Analyst","Accountant","Auditor","Finance Manager","Investment Analyst","Consultant","Other"];
export default function Signup(){
 const {signup}=useAuth();const navigate=useNavigate();const [accountType,setAccountType]=useState<Role>("Individual");const [name,setName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [professionalRole,setProfessionalRole]=useState<ProfessionalRole>("Other");const [terms,setTerms]=useState(false);const [error,setError]=useState("");
 const submit=async(e:FormEvent)=>{e.preventDefault();setError("");if(password!==confirm)return setError("Passwords do not match.");if(password.length<6)return setError("Password must be at least 6 characters.");if(!terms)return setError("Accept the terms to continue.");try{await signup(name,email,password,professionalRole,accountType);navigate(accountType==="Individual"?"/individual":"/");}catch(err){setError(err instanceof Error?err.message:"Signup failed");}};
 const description=accountType==="Individual"?"Personal income, assets, tax and financial management.":accountType==="Finance User"?"Small-business finance for shops, freelancers and business owners.":"Professional workspace for CAs, CSs, auditors and other finance professionals.";
 return <div className="auth-shell"><div className="auth-brand"><div className="brand-mark large"><Sparkles size={22}/></div><div><div className="brand-name">FINOTECH</div><div className="brand-sub">AI FINANCE OS</div></div></div><div className="auth-card wide-card"><Link className="back-link" to="/login"><ArrowLeft size={15}/> Back to sign in</Link><div className="eyebrow">CREATE ACCOUNT</div><h1>Choose your Finpro workspace</h1><div className="account-type-grid">
 <button type="button" className={accountType==="Individual"?"account-type selected":"account-type"} onClick={()=>setAccountType("Individual")}><strong>Individual User</strong><span>For salaried individuals managing income, assets, investments and ITR.</span></button>
 <button type="button" className={accountType==="Finance User"?"account-type selected":"account-type"} onClick={()=>setAccountType("Finance User")}><strong>Finance User</strong><span>For shops, grocery owners, freelancers and small businesses.</span></button>
 <button type="button" className={accountType==="Professional User"?"account-type selected":"account-type"} onClick={()=>setAccountType("Professional User")}><strong>Professional User</strong><span>For CAs, CSs, auditors, CFAs and finance advisory professionals.</span></button>
 </div><p className="auth-muted">{description}</p><form onSubmit={submit} className="form-grid"><label>Full name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label>{accountType==="Professional User"&&<label>Professional role<select value={professionalRole} onChange={e=>setProfessionalRole(e.target.value as ProfessionalRole)}>{professionalRoles.map(r=><option key={r}>{r}</option>)}</select></label>}<label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={6} required/></label><label>Confirm password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={6} required/></label><label className="checkbox-label full"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/> I agree to the terms and understand that tax outputs require review.</label>{error&&<div className="error-box full">{error}</div>}<button className="btn btn-primary wide full" type="submit">Create {accountType.toLowerCase()} account</button></form></div><div className="auth-footer">Your account type controls the workspace and permissions you receive.</div></div>;
}